### ISSUE TITLE
Binary space partitioning

### ISSUE THREAD

**Issue by ilia-glushchenko** [Godlike/Pegasus#72]
Investigate examples from 2005 Ericson - Real-Time Collision Detection, chapter 7, 8.

**Comment by ilia-glushchenko** [comment]
Investigate options from Real-Time Collision Detection, chapters: 7, 8

**Comment by ilia-glushchenko** [comment]
Questions to investigate: 

What's binary space partition tree? 
What's it used for?
How does it differ from kd tree and oc tree?
What are the up sides and down sides of it compare to kd tree and oc tree?
When usage of bsp, oc or kd trees is appropriate and when it's not?

What's uniform and non-uniform grids?
How do they differ?
When usage of one or another is appropriate and when it's not?

Are they any other solutions for space partition tasks?

**Comment by Warezovvv** [comment]
Can you do a blog post after?

**Comment by ilia-glushchenko** [comment]
@Warezovvv Yep

**Comment by Warezovvv** [comment]
@ilia-glushchenko So can you add a blog post as part of this task?

**Comment by ilia-glushchenko** [comment]
@Warezovvv I will publish the results and link it here.

**Comment by ilia-glushchenko** [comment]
https://github.com/Godlike/Arion/projects/1 Migration.
